FROM node:18-alpine as BUILD_IMAGE
WORKDIR /app

COPY package.json .

RUN npm install

ARG VITE_BACKEND_SERVICE_URL
ARG VITE_ANAMAYA_APPLICATION_ID
ARG VITE_STE_APPLICATION_ID
ARG VITE_USER_SERVICE_URL

RUN echo "VITE_BACKEND_SERVICE_URL=${VITE_BACKEND_SERVICE_URL}\nVITE_ANAMAYA_APPLICATION_ID=${VITE_ANAMAYA_APPLICATION_ID}\nVITE_STE_APPLICATION_ID=${VITE_STE_APPLICATION_ID}\nVITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}" > .env

COPY . .

RUN npm run build

FROM node:18-alpine as PRODUCTION_IMAGE

WORKDIR /app

COPY --from=BUILD_IMAGE /app/dist/ /app/dist/

COPY package.json .
COPY vite.config.ts .

RUN npm install typescript

EXPOSE 5175

CMD ["npm", "run", "serve"]

